POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Pythonic Ways to Write Clean Code",
    "author": "Alex Programmer",
    "url": "https://example.com/pythonic-clean-code",
    "likes": 25
}